# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]

jobs:
  TestAndPush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

#     - name: Test
#       run: test.sh
      
    - name: Set git configs
      run: |
        git config --global user.email "llll@example.com"
        git config --global user.name "Github Actions CI"

    - name: Revert this branch
      run: git reset --hard HEAD

    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Push to master
      if: success()
      run: |
        git fetch
        git pull origin develop --allow-unrelated-histories
        git push origin master
        
