name: Post processing of the PR

on:
  pull_request:
    types: [ closed ]

jobs:
  closed-pr:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update submodules
      run: git submodule update --remote

    - name: Close issue
      uses: ./.github/actions/act_access_ghra
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        url: ${{ github.event.issue.url }}
        method: 'PATCH'
        arg: '{"state"="close"}'