name: Delete feature branch

on:
  workflow_dispatch: 
  issues:
    types: [ closed, deleted ]

jobs:
  delete-feature:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set git configs
      run: |
        git config --global user.email "llll@example.com"
        git config --global user.name "Github Actions CI"
    
    - name: Delete branch
      shell: bash
      run: |
        git push --delete origin feature/${{ github.event.issue.number }} || :
