name: Delete feature branch

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-feature:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        repository: 'begyyal/act_delete_feature'

    - name: Delete feature branches
      uses: ./
      with:
        token: ${{ secrets.PAT_REPO }}
        repos: ${{ github.repository }}
