# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Create feature branch

on:
  issues:
    types: [ closed, deleted ]

jobs:
  delete-feature:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2

    - name: Set git configs
      run: |
        git config --global user.email "llll@example.com"
        git config --global user.name "Github Actions CI"
    
    - name: Delete branch
      shell: bash
      run: |
        git push --delete origin feature/${{ github.event.issue.number }} || :
