name: Delete feature branch

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-feature:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true

    - name: Delete feature branches
      uses: ./.github/actions/act_delete_feature
      with:
        token: ${{ secrets.PAT_REPO }}
        repos: ${{ github.repository }}
