name: Update process of the PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize ]

jobs:
  sync-pr:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: 'begyyal/act_revise_comments'

    - shell: bash
      run: |
        cat ./.git/config
        echo '========'
        cat ~/.gitconfig

    # - name: Extract the issue no
    #   id: ready
    #   shell: bash
    #   run: |
    #     branch=${{github.head_ref}}
    #     echo "::set-output name=issue-no::${branch#feature/}"

    # - name: Revise target feature's comments
    #   uses: ./
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     repos: ${{ github.repository }}
    #     issueNo: ${{ steps.ready.outputs.issue-no }}
